name: Build

on: 
  push:
    branches: 
      - '*'
      - '*/**'
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - 'LICENSE'
      - 'CHANGELOG.md'
      - 'tools/**'


jobs:
  selfhosted:
    concurrency: ${{ matrix.remote_host }}
    runs-on: [self-hosted, server]
    strategy:
      fail-fast: false
      matrix:
        remote_host: [freebsd-13.1, freebsd-14]
        
    steps:
    - name: Run remote build
      run: |
        "$RUNNER_TOOLS_PATH"/run-agent gh-${{ matrix.remote_host }} <<'EOF'
        set -e
        if [ ! -d work/ptl ]; then
          git clone https://github.com/gershnik/ptl.git work/ptl
        fi
        cd work/ptl
        git fetch --all
        git fetch -f --prune --tags
        git reset --hard ${{ github.sha }}
        rm -rf out
        cmake -S . -B out -DCMAKE_BUILD_TYPE=RelWithDebInfo 
        cmake --build out --target run-test
        EOF

  local:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: macos-latest
        - os: windows-latest
        - os: ubuntu-latest
          cc: gcc-11
          cxx: g++-11
        - os: ubuntu-latest
          cc: gcc-12
          cxx: g++-12
        - os: ubuntu-latest
          cc: gcc-13
          cxx: g++-13
        # - os: ubuntu-latest
        #   cc: gcc-14
        #   cxx: g++-14
        # - os: ubuntu-latest
        #   cc: clang-13
        #   cxx: clang++-13
        # - os: ubuntu-latest
        #   cc: clang-14
        #   cxx: clang++-14
        - os: ubuntu-latest
          cc: clang-15
          cxx: clang++-15
        - os: ubuntu-latest
          cc: clang-16
          cxx: clang++-16
        - os: ubuntu-latest
          cc: clang-17
          cxx: clang++-17
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: System Setup
      shell: bash
      run: |
        if [[ '${{ matrix.os }}' == 'ubuntu-latest' ]]; then
          if [[ '${{ matrix.cc }}' == 'clang-15' ]]; then
            sudo apt-get update
            sudo apt-get install -y clang-15 clang++-15
          fi

          if [[ '${{ matrix.cc }}' == 'clang-16' ]]; then
            wget https://apt.llvm.org/llvm.sh
            chmod u+x llvm.sh
            sudo ./llvm.sh 16
          fi

          if [[ '${{ matrix.cc }}' == 'clang-17' ]]; then
            wget https://apt.llvm.org/llvm.sh
            chmod u+x llvm.sh
            sudo ./llvm.sh 17
          fi

          if [[ '${{ matrix.cc }}' == 'gcc-13' ]]; then
            sudo apt-get update
            sudo apt-get install -y gcc-13 g++-13
          fi

          if [[ '${{ matrix.cc }}' == 'gcc-14' ]]; then
            sudo apt-get update
            sudo apt-get install -y gcc-14 g++-14
          fi
        fi

    - name: Configure
      shell: bash
      run: |
          if [[ '${{ matrix.cc }}' != '' ]]; then
            export CC=${{ matrix.cc }}
          fi
          if [[ '${{ matrix.cxx }}' != '' ]]; then
            export CXX=${{ matrix.cxx }}
          fi
          cmake -S . -B out -DCMAKE_BUILD_TYPE=RelWithDebInfo 

    - name: Build
      run: |
          cmake --build out --target run-test

  mingw:
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure
      shell: cmd
      run: |
          PATH=C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin;%PATH%
          cmake -G "MinGW Makefiles" -S . -B out -DCMAKE_BUILD_TYPE=RelWithDebInfo 

    - name: Build
      shell: cmd
      run: |
          PATH=C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin;%PATH%
          cmake --build out --target run-test

  cygwin:
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Cygwin
      uses: egor-tensin/setup-cygwin@v4
      with:
        packages: cmake ninja gcc-g++ cygwin-devel

    - name: Configure
      shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
      run: |
          cd ${GITHUB_WORKSPACE}
          cmake -GNinja -S . -B out -DCMAKE_BUILD_TYPE=RelWithDebInfo 

    - name: Build
      shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
      run: |
          cd ${GITHUB_WORKSPACE}
          cmake --build out --target run-test

  android:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [25.2.9519653]
        api: [21, 30]    
        arch: [x86_64]
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Enable KVM
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm

    - name: AVD cache
      uses: actions/cache@v4
      id: avd-cache
      with:
        path: |
          ~/.android/avd/*
          ~/.android/adb*
        key: avd-${{ matrix.version }}-${{ matrix.arch }}-30

    - name: Create AVD and generate snapshot for caching
      if: steps.avd-cache.outputs.cache-hit != 'true'
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        arch: ${{matrix.arch}}
        target: google_apis
        ndk: ${{ matrix.version }}
        force-avd-creation: false
        emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        disable-animations: false
        script: echo "Generated AVD snapshot for caching."

    - name: Run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        arch: ${{matrix.arch}}
        target: google_apis
        ndk: ${{ matrix.version }}
        force-avd-creation: false
        emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        disable-animations: true
        script: |
            cmake -S . -B out -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_TOOLCHAIN_FILE:FILEPATH=$ANDROID_SDK_ROOT/ndk/${{ matrix.version }}/build/cmake/android.toolchain.cmake -DANDROID_ABI:STRING=${{ matrix.arch }} -DANDROID_PLATFORM:STRING=${{ matrix.api }} -DANDROID_STL:STRING=c++_static
            cmake --build out --target run-test

