name: Build

on: 
  push:
    branches: 
      - '*'
      - '*/**'
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - 'LICENSE'
      - 'CHANGELOG.md'
      - 'tools/**'


jobs:
  selfhosted:
    concurrency: ${{ matrix.remote_host }}
    runs-on: [self-hosted, server]
    strategy:
      fail-fast: false
      matrix:
        include: 
        - remote_host: freebsd-13.1
        
    steps:
    - name: Run remote build
      run: |
        "$RUNNER_TOOLS_PATH"/run-agent gh-${{ matrix.remote_host }} <<'EOF'
        set -e
        if [ ! -d work/ptl ]; then
          git clone https://github.com/gershnik/ptl.git work/ptl
        fi
        cd work/ptl
        git fetch --all
        git fetch -f --prune --tags
        git reset --hard ${{ github.sha }}
        [ -d "out" ] || mkdir out
        cmake -S . -B out -DCMAKE_BUILD_TYPE=RelWithDebInfo 
        cmake --build out --target run-test
        EOF

  local:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include: 
        - os: ubuntu-latest
        - os: macos-latest
        - os: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # - name: Collect System Info
    #   id: system-info
    #   uses: kenchan0130/actions-system-info@master

    # - name: Cache Build Dir
    #   id: cache-build-dir
    #   uses: actions/cache@v3
    #   with:
    #     path: out
    #     key: ${{ runner.os }}-${{ steps.system-info.outputs.release }}-out

    - name: Configure
      run: |
          cmake -E make_directory out
          cmake -S . -B out -DCMAKE_BUILD_TYPE=RelWithDebInfo 

    - name: Build
      run: |
          cmake --build out --target run-test

