name: Build

on: 
  push:
    branches: 
      - '*'
      - '*/**'
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - 'LICENSE'
      - 'CHANGELOG.md'
      - 'tools/**'


jobs:
  selfhosted:
    concurrency: ${{ matrix.remote_host }}
    runs-on: [self-hosted, server]
    strategy:
      fail-fast: false
      matrix:
        include: 
        - remote_host: freebsd-13.1
        
    steps:
    - name: Run remote build
      run: |
        "$RUNNER_TOOLS_PATH"/run-agent gh-${{ matrix.remote_host }} <<'EOF'
        set -e
        if [ ! -d work/ptl ]; then
          git clone https://github.com/gershnik/ptl.git work/ptl
        fi
        cd work/ptl
        git fetch --all
        git fetch -f --prune --tags
        git reset --hard ${{ github.sha }}
        [ -d "out" ] || mkdir out
        cmake -S . -B out -DCMAKE_BUILD_TYPE=RelWithDebInfo 
        cmake --build out --target run-test
        EOF

  local:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include: 
        - os: ubuntu-latest
        - os: macos-latest
        - os: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Collect System Info
      id: system-info
      uses: kenchan0130/actions-system-info@master

    - name: Cache Build Dir
      id: cache-build-dir
      uses: actions/cache@v3
      with:
        path: out
        key: ${{ runner.os }}-${{ steps.system-info.outputs.release }}-out

    - name: Configure
      shell: bash
      run: |
          cmake -E make_directory out
          cmake -S . -B out -DCMAKE_BUILD_TYPE=RelWithDebInfo 

    - name: Build
      run: |
          cmake --build out --target run-test

  mingw:
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Collect System Info
      id: system-info
      uses: kenchan0130/actions-system-info@master

    - name: Cache Build Dir
      id: cache-build-dir
      uses: actions/cache@v3
      with:
        path: out
        key: ${{ runner.os }}-${{ steps.system-info.outputs.release }}-mingw-out

    - name: Configure
      shell: cmd
      run: |
          cmake -E make_directory out
          PATH=C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin;%PATH%
          cmake -G "MinGW Makefiles" -S . -B out -DCMAKE_BUILD_TYPE=RelWithDebInfo 

    - name: Build
      shell: cmd
      run: |
          PATH=C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin;%PATH%
          cmake --build out --target run-test

  cygwin:
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Cygwin
      uses: egor-tensin/setup-cygwin@v4
      with:
        packages: cmake ninja gcc-g++ cygwin-devel

    - name: Collect System Info
      id: system-info
      uses: kenchan0130/actions-system-info@master

    - name: Cache Build Dir
      id: cache-build-dir
      uses: actions/cache@v3
      with:
        path: out C:\tools\cygwin
        key: ${{ runner.os }}-${{ steps.system-info.outputs.release }}-cygwin-out

    - name: Configure
      shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
      run: |
          cd ${GITHUB_WORKSPACE}
          cmake -E make_directory out
          cmake -GNinja -S . -B out -DCMAKE_BUILD_TYPE=RelWithDebInfo 

    - name: Build
      shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
      run: |
          cd ${GITHUB_WORKSPACE}
          cmake --build out --target run-test

  android:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: reactivecircus/android-emulator-runner@v2
      env:
        NDK_VER: 23.1.7779620
        NDK_ARCH: x86_64
        NDK_API: 29
      with:
        api-level: ${{env.NDK_API}}
        arch: ${{env.NDK_ARCH}}
        target: google_apis
        ndk: ${{env.NDK_VER}}
        script: |
            cmake -E make_directory out
            cmake -S . -B out -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_TOOLCHAIN_FILE:FILEPATH=$ANDROID_SDK_ROOT/ndk/$NDK_VER/build/cmake/android.toolchain.cmake -DANDROID_ABI:STRING=$NDK_ARCH -DANDROID_PLATFORM:STRING=$NDK_API -DANDROID_STL:STRING=c++_static
            cmake --build out --target run-test

